//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MFCExHttpsSrv.rc
//
#define IDC_Add                         3
#define IDC_CreateSimple2               4
#define IDC_Del                         4
#define IDC_Apply                       5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_MFCEXHTTPSSRV_FORM          101
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_WinpacheTYPE                130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDI_DockTestApi_HC              177
#define IDB_CLASS_VIEW_24               178
#define IDI_DockOdbc_HC                 178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDD_ImageSizeAdjust             313
#define IDB_WRITELARGE1                 313
#define IDD_SslSetting                  314
#define IDD_OdbcSetting                 315
#define IDD_Clustering                  319
#define IDD_DockTestApi                 322
#define IDD_DockOdbc                    323
#define IDC_ExList                      1000
#define IDC_UUD                         1001
#define IDC_PWD                         1002
#define IDC_Close                       1003
#define IDC_Input                       1004
#define IDC_DSN                         1004
#define IDC__certificate                1004
#define IDC_Output                      1005
#define IDC_ConnectDB                   1005
#define IDC_PWD2                        1005
#define IDC__privatekey                 1005
#define IDC__dhparam                    1006
#define IDC_LinkToGithub                1007
#define IDC_BtnCertificate              1008
#define IDC_BtnPrivate                  1009
#define IDC_OdbcSetting                 1009
#define IDC_BtnDhparam                  1010
#define IDC_NPM                         1010
#define IDC_STATIC_PWD                  1011
#define IDC__port                       1011
#define IDC_MonitorList                 1012
#define IDC_Elapsed                     1013
#define IDC__prvpwd                     1014
#define IDC_url                         1015
#define IDC__bSSL                       1015
#define IDC_action                      1016
#define IDC__CacheLife                  1016
#define IDC_mode                        1017
#define IDC__ODBCDSN                    1017
#define IDC_SrcImagePath                1018
#define IDC_BtnRootLocal                1019
#define IDC_Width                       1019
#define IDC_Clustering                  1019
#define IDC_Height                      1020
#define IDC__ApiURL                     1020
#define IDC_STATIC1                     1021
#define IDC_Simulation                  1022
#define IDC__note                       1022
#define IDC_STATICDB                    1023
#define IDC_ExceptDir                   1023
#define IDC_BtnUploadLocal              1025
#define IDC__uploadLocal                1026
#define IDC_BtnSslSetting               1027
#define IDC__rootLocal                  1028
#define IDC_RunApi                      1029
#define IDC__bStaticCache               1029
#define IDC_Select                      1030
#define IDC__defFile                    1030
#define IDC_Parallel                    1031
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_FreeLibrary                  32771
#define ID_MIGRATION_IMAGESIZEADJUST    32772
#define ID_Start                        32773
#define ID_Stop                         32774
#define ID_BUTTON4                      32775
#define ID_VIEW_Outwnd                  32776
#define ID_Restart                      32777
#define ID_StartDB                      32778
#define ID_DownloadMariaDB              32780
#define ID_DownloadMariaODBC            32781
#define ID_TestAPI                      32782
#define ID_RunClient                    32783
#define ID_DownloadOpenSSL              32784
#define ID_VIEW_PROPERTIES              32785
#define ID_ViewTestAPI                  32786
#define ID_SiteProject                  32787
#define ID_OdbcSetting                  32788
#define ID_VisualStudioDownload         32789
#define ID_BuildProject                 32790
#define ID_InstallMariaDB               32791
#define ID_InstallMariaODBC             32792
#define ID_NewServer                    32793
#define ID_TableBasic                   32794
#define ID_CreateDatabase               32795
#define ID_InitODBC                     32796
#define ID_TableSample                  32797
#define ID_DockOdbcSetting              32798
#define ID_OdbcConnect                  32800
#define ID_CHECK3                       32801
#define ID_VIEW_TestAPI                 32803
#define ID_GoToProject                  32804
#define ID_GotoOutput                   32805
#define ID_RunHeidiSQL                  32806
#define ID_CopyRequestList              32807
#define ID_CopyRequest                  32807
#define ID_CopyOutput                   32808
#define ID_SiteStart                    32809
#define ID_SiteStop                     32810
#define ID_EDIT_CONNECTSITEDB           32812
#define ID_ConnectSiteDB                32813
#define ID_SiteRestart                  32814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        322
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
