//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MFCSmpApp4.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_MFCSMPAPP4_FORM             101
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_SmpApp4TYPE                 130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDI_DockCustomList_HC           169
#define IDB_EXPLORER_24                 170
#define IDI_DockMyHistory_HC            170
#define IDR_SORT                        171
#define IDI_DockMyPetList_HC            171
#define IDB_SORT_24                     172
#define IDI_DockPetDetail_HC            172
#define IDR_POPUP_SORT                  173
#define IDI_DockPetChecks_HC            173
#define IDR_POPUP_EXPLORER              174
#define IDI_DockScheduleDetail_HC       174
#define IDB_FILE_VIEW                   175
#define IDI_DockOrder_HC                175
#define IDB_FILE_VIEW_24                176
#define IDI_DockProducts_HC             176
#define IDB_CLASS_VIEW                  177
#define IDI_DockOptions_HC              177
#define IDB_CLASS_VIEW_24               178
#define IDI_DockCustomDetail_HC         178
#define IDR_MENU_IMAGES                 179
#define IDI_DockCustomHistory_HC        179
#define IDB_MENU_IMAGES_24              180
#define IDI_DockWorkLogList_HC          180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define IDR_POPUP_Order                 201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDD_DockEx2                     311
#define IDD_DockCustomDetail            312
#define IDD_DockCustomHistory           313
#define IDD_DockMyHistory               314
#define IDD_DockMyPetChecks             315
#define IDD_DockPetChecks               315
#define IDD_DockPetDetail               316
#define IDD_DockMyPetList               317
#define IDD_DockScheduleDetail          318
#define IDD_DockCustomList              319
#define IDD_DockOrder                   320
#define IDB_ViewBG                      321
#define IDD_DockProducts                321
#define IDD_DockOptions                 322
#define IDD_DockWorkLogList             323
#define IDB_BITMAP3                     324
#define IDB_BITMAP4                     325
#define IDB_BITMAP5                     326
#define IDB_BITMAP6                     327
#define IDB_BITMAP7                     328
#define IDD_LogIn                       330
#define IDD_DockOptions1                331
#define IDC_LIST1                       1000
#define IDC_ReadTimeTable               1001
#define IDC_BUTTON1                     1002
#define IDC_Refresh                     1002
#define IDC_BUTTON2                     1003
#define IDC_Clear                       1003
#define IDC_BUTTON3                     1004
#define IDC_AddProd                     1004
#define IDC_LIST4                       1005
#define IDC_LIST3                       1005
#define IDC_MFCBUTTON1                  1006
#define IDC_BUTTON4                     1006
#define IDC_AddOption                   1006
#define IDC_MFCPROPERTYGRID1            1007
#define IDC_BUTTON5                     1008
#define IDC_AddSchedule                 1008
#define IDC_BUTTON6                     1009
#define IDC_Payment                     1009
#define IDC_LIST2                       1016
#define IDC_STATICBG                    1017
#define IDC_Read                        1018
#define IDC_AddToOrder                  1019
#define IDC_AddPet                      1019
#define IDC_AddPet2                     1020
#define IDC_StartOrder                  1020
#define IDC_AddMyPet                    1020
#define IDC_MyPetList                   1021
#define IDC_AddToOrder2                 1021
#define IDC_NewOrder                    1021
#define IDC_Blink                       1022
#define IDC_Filter                      1023
#define IDC_STATIC_top                  1025
#define IDC_OrderStart                  1026
#define IDC_LogInID                     1027
#define IDC_PcPwd                       1028
#define IDC_CertCode                    1029
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_ViewDockCustomDetail         32771
#define ID_ViewDockCustomHistory        32772
#define ID_ViewDockMyHistory            32773
#define ID_ViewDockMyPetList            32774
#define ID_ViewDockMyPetChecks          32776
#define ID_ViewDockSheduleDetail        32777
#define ID_CONTEXT_CustomDetail         32778
#define ID_BUTTON2                      32779
#define ID_BUTTON3                      32780
#define ID_AddPet                       32780
#define ID_ViewDockScheduleDetail       32781
#define ID_ViewDockPetDetail            32782
#define ID_CONTEXT_TimeTable            32783
#define ID_CHECK2                       32784
#define ID_StaffDetail                  32784
#define ID_COMBO2                       32785
#define ID_CHECK3                       32786
#define ID_OrderList                    32786
#define ID_PROGRESS2                    32787
#define ID_CONTEXT_ScheduleDetail       32788
#define ID_ReadTimeTable                32789
#define ID_RefreshTimeTable             32790
#define ID_ClearTimeTable               32791
#define ID_AddOrder                     32797
#define ID_AddSchedule                  32798
#define ID_DelSchedule                  32799
#define ID_UndoSchedule                 32800
#define ID_RedoSchedule                 32801
#define ID_StaffList                    32802
#define ID_SalesList                    32803
#define ID_ReviewfDetail                32804
#define ID_ReviewList                   32805
#define ID_CustomList                   32805
#define ID_ViewDockProducts             32806
#define ID_ViewDockOptions              32808
#define ID_ViewDockOrder                32809
#define ID_SLIDER_Zoom                  32810
#define ID_AlwaysSyncSD                 32811
#define ID_32812                        32812
#define ID_32813                        32813
#define ID_Menu                         32814
#define ID_PopOrder_AddPet              32815
#define ID_PopOrder_DelPet              32816
#define ID_PopOrder_AddProd             32817
#define ID_PopOrder_DelProd             32818
#define ID_PopOrder_AddOpt              32819
#define ID_PopOrder_DelOpt              32820
#define ID_CONTEXT_Order                32821
#define ID_AddProd                      32822
#define ID_AddOption                    32823
#define ID_Payment                      32824
#define ID_CONTEXT_MyPets               32825
#define ID_Read                         32826
#define ID_NewOrder                     32827
#define ID_AddToOrder                   32828
#define ID_DelPet                       32829
#define ID_DelProd                      32830
#define ID_DelOption                    32831

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        332
#define _APS_NEXT_COMMAND_VALUE         32833
#define _APS_NEXT_CONTROL_VALUE         1030
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
