//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SuareSimul.rc
//
#define IDC_Mix                         3
#define IDC_ReplaySample                3
#define IDC_Close                       4
#define IDC_TrySame                     4
#define IDC_Solve                       5
#define IDC_Mix3                        5
#define IDC_Mix2                        6
#define IDC_Reset                       6
#define IDC_Mix4                        7
#define IDC_Start                       7
#define IDC_Lf0                         10
#define IDC_Lf1                         11
#define IDC_Lf2                         12
#define IDC_Lf3                         13
#define IDC_Lf4                         14
#define IDC_Lf5                         15
#define IDM_ABOUTBOX                    0x0010
#define IDM_User                        0x0011
#define IDM_Ranking                     0x0012
#define IDC_Rt0                         20
#define IDC_Rt1                         21
#define IDC_Rt2                         22
#define IDC_Rt3                         23
#define IDC_Rt4                         24
#define IDC_Rt5                         25
#define IDC_Up0                         30
#define IDC_Up1                         31
#define IDC_Up2                         32
#define IDC_Up3                         33
#define IDC_Up4                         34
#define IDC_Up5                         35
#define IDC_Up6                         36
#define IDC_Up7                         37
#define IDC_Up8                         38
#define IDC_Dn0                         40
#define IDC_Dn1                         41
#define IDC_Dn2                         42
#define IDC_Dn3                         43
#define IDC_Dn4                         44
#define IDC_Dn5                         45
#define IDC_Dn6                         46
#define IDC_Dn7                         47
#define IDC_Dn8                         48
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SUARESIMUL_DIALOG           102
#define IDP_OLE_INIT_FAILED             102
#define IDS_UserInformation             103
#define IDS_Ranking                     104
#define IDS_Second                      105
#define IDS_WillYouClose                106
#define IDS_Ready                       107
#define IDS_Nickname                    108
#define IDS_TimeSec                     109
#define IDS_CantConnect                 110
#define IDS_RegTime                     111
#define IDC_NicknameDuplicated          112
#define IDS_NicknameDuplicated          112
#define IDS_Standby                     113
#define IDS_ReplayDone                  114
#define IDS_Finished                    115
#define IDS_Start                       116
#define IDS_AppName                     117
#define IDR_MAINFRAME                   128
#define IDD_DlgUser                     133
#define IDD_DlgRanking                  136
#define IDB_PNG_white                   138
#define IDB_PNG_green                   139
#define IDB_PNG_yellow                  140
#define IDB_PNG_blue                    141
#define IDB_PNG_orange                  142
#define IDB_PNG_red                     143
#define IDB_PNG_right                   144
#define IDB_PNG_bottom                  145
#define IDB_PNG_left                    146
#define IDB_PNG_top                     147
#define IDB_PNG_rivet                   149
#define IDC_Cell_00                     1000
#define IDC_Cell_01                     1001
#define IDC_Cell_02                     1002
#define IDC_Cell_03                     1003
#define IDC_Cell_04                     1004
#define IDC_Cell_05                     1005
#define IDC_Cell_06                     1006
#define IDC_Cell_07                     1007
#define IDC_Cell_08                     1008
#define IDC_Cell_10                     1010
#define IDC_Cell_11                     1011
#define IDC_Cell_12                     1012
#define IDC_Cell_13                     1013
#define IDC_Cell_14                     1014
#define IDC_Cell_15                     1015
#define IDC_Cell_16                     1016
#define IDC_Cell_17                     1017
#define IDC_Cell_18                     1018
#define IDC_Cell_20                     1020
#define IDC_Cell_21                     1021
#define IDC_Cell_22                     1022
#define IDC_Cell_23                     1023
#define IDC_Cell_24                     1024
#define IDC_Cell_25                     1025
#define IDC_Cell_26                     1026
#define IDC_Cell_27                     1027
#define IDC_Cell_28                     1028
#define IDC_Cell_30                     1030
#define IDC_Cell_31                     1031
#define IDC_Cell_32                     1032
#define IDC_Cell_33                     1033
#define IDC_Cell_34                     1034
#define IDC_Cell_35                     1035
#define IDC_Cell_36                     1036
#define IDC_Cell_37                     1037
#define IDC_Cell_38                     1038
#define IDC_Cell_40                     1040
#define IDC_Cell_41                     1041
#define IDC_Cell_42                     1042
#define IDC_Cell_43                     1043
#define IDC_Cell_44                     1044
#define IDC_Cell_45                     1045
#define IDC_Cell_46                     1046
#define IDC_Cell_47                     1047
#define IDC_Cell_48                     1048
#define IDC_Cell_50                     1050
#define IDC_Cell_51                     1051
#define IDC_Cell_52                     1052
#define IDC_Cell_53                     1053
#define IDC_Cell_54                     1054
#define IDC_Cell_55                     1055
#define IDC_Cell_56                     1056
#define IDC_Cell_57                     1057
#define IDC_Cell_58                     1058
#define IDC_Cell_60                     1060
#define IDC_Cell_61                     1061
#define IDC_Cell_62                     1062
#define IDC_Cell_63                     1063
#define IDC_Cell_64                     1064
#define IDC_Cell_65                     1065
#define IDC_Cell_66                     1066
#define IDC_Cell_67                     1067
#define IDC_Cell_68                     1068
#define IDC_Cell_70                     1070
#define IDC_Cell_71                     1071
#define IDC_Cell_72                     1072
#define IDC_Cell_73                     1073
#define IDC_Cell_74                     1074
#define IDC_Cell_75                     1075
#define IDC_Cell_76                     1076
#define IDC_Cell_77                     1077
#define IDC_Cell_78                     1078
#define IDC_Cell_80                     1080
#define IDC_Cell_81                     1081
#define IDC_Cell_82                     1082
#define IDC_Cell_83                     1083
#define IDC_Cell_84                     1084
#define IDC_Cell_85                     1085
#define IDC_Cell_86                     1086
#define IDC_Cell_87                     1087
#define IDC_Cell_88                     1088
#define IDC_COMBO1                      1100
#define IDC_Spaces                      1101
#define IDC_Time                        1102
#define IDC_Count                       1103
#define IDS_Count                       1103
#define IDC_Color                       1104
#define IDS_Complete                    1104
#define IDC_email                       1105
#define IDS_Complete2                   1105
#define IDS_FileFormatError             1105
#define IDC_ReplaySpeed                 1105
#define IDC_EDIT2                       1106
#define IDC_SNS                         1106
#define IDC_BUTTON1                     1106
#define IDC_User                        1106
#define IDC_LIST1                       1107
#define IDC_Nickname                    1107

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1108
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
